# 关闭配置缓存，解决NDK序列化报错
org.gradle.configuration-cache=false
# 禁用Develocity监控注入
systemProp.develocity.injection.enabled=false
# 阻止自动加载构建扫描插件
systemProp.gradle.plugin.load.blocklist=com.gradle.develocity
# 给JAXB模块开放反射权限，解决instrument访问失败
org.gradle.jvmargs=--add-opens=java.xml.bind/javax.xml.bind.annotation=ALL-UNNAMED
